name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: openssl
      - name: test
        run: |
          composer install
          composer dumpautoload -o
          ./vendor/bin/phpunit --bootstrap test/ciautoload.php  --verbose test
          
          
